In [3]:
# Q-1 --> Write a Python program to create an int, character and float array using array function.
import numpy as np
# int
a = np.array([1,2,3,4,5], int)
print(a)
#float
a1 = np.array([1.0,2.5,3.5,10.5,10], float)
print(a1)
#character
a2 = np.array(['A', "Hello World", 'a'], str)
print(a2)


[1 2 3 4 5]
[ 1.   2.5  3.5 10.5 10. ]
['A' 'Hello World' 'a']


In [5]:
# Q-2 -->Create an integer array from a range between 100 to 200 such that the difference between each element is 15.
import numpy as np
a3 = np.arange(100,200,15)
print(a3)

[100 115 130 145 160 175 190]


In [16]:
# Q-3 -->Create array for following:
# 1 --> 1D array of 10 elements all initialized to 0
import numpy as np
a4 = np.zeros(10,int)
print(a4)

# 2 --> 2D array of 5 X 2 , with all elements initialized to 0
a5 = np.zeros(10, int)
a5 = a5.reshape(5,2)
print(a5)

# 3 --> 1D array of 6 elements all initialized to 1
a6 = np.ones(6, int)
print(a6)

# 4 --> 2D array of 2 X 3 , with all elements initialized to 1
a7 = np.ones(6, int)
a7 = a7.reshape(2,3)
print(a7)

# 5 --> 1D array of 8 elements with all initialized to 8
a8 = np.ones(8, int)*8
print(a8)


[0 0 0 0 0 0 0 0 0 0]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[1 1 1 1 1 1]
[[1 1 1]
 [1 1 1]]
[8 8 8 8 8 8 8 8]


In [20]:
# Q-4 -->Create an array of 10 values from 1 to 5 evenly spaced on a linear scale.
import numpy as np
a9 = np.linspace(1,5,10)
print(a9)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [18]:
# Q-5 -->Create an array of 10 values from 1 to 5 evenly spaced on log scale.
import numpy as np
a10 = np.logspace(1,5,10)
print(a10)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


In [24]:
# Q-6 -->Create an identity matrix of size 10 X 10.
import numpy as np
a11 = np.eye(10)
print(a11)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
# Q-7 -->Get a 4 X 4 array of samples from the standard normal distribution using normal.
import numpy as np
n,m = int(input("Enter n :")), int(input("Enter m :"))
a12 = np.random.normal(size = (n,m))
print(a12)


[[ 0.46592749  1.26559989 -0.82233407]
 [ 1.07537446 -0.0839332  -0.36786447]
 [ 0.15131651  1.09237195 -0.79382603]]


In [31]:
# Q-8 -->Demonstrate the use of len() function with an example.
import numpy as np
a13 = np.array([1,2,3,4,5])
a14 = np.array([[1,2],[2,3],[3,4],[4,5]])
print(len(a13))
print(len(a14))


5
4


In [40]:
# Q-9 --> Demonstrate the use of following attributes with a sample program:
import numpy as np
a15 = np.arange(1,10,5)
a16 = np.array([[1,2,3],[4,5,6]])
print(a15)
print(a16)

# ndim
print("The dimension is :",a15.ndim)
print("The dimension is :",a16.ndim)

# shape
print("The shape is :",a15.shape)
print("The shape is :",a16.shape)

# itemsize
print("The memory size is :",a15.itemsize)
print("The memory size is :",a16.itemsize)

# dtype
print("The type of element is :",a15.dtype)
print("The type of element is :",a16.dtype)

# size
print("The size is :",a15.size)
print("The size is :",a16.size)

[1 6]
[[1 2 3]
 [4 5 6]]
The dimension is : 1
The dimension is : 2
The shape is : (2,)
The shape is : (2, 3)
The memory size is : 4
The memory size is : 4
The type of element is : int32
The type of element is : int32
The size is : 2
The size is : 6
